apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.my-service.name }}
spec:
  selector:
    {{- with .Values.my-service.appSelector }}
    matchLabels:
      {{- toYaml . | nindent 6 }}
    {{- end }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.my-service.port.targetPort }}
  type: LoadBalancer

---
# apiVersion: v1
# kind: Service
# metadata:
#   name: my-service
# spec:
#   selector:
#     app: my-app
#   ports:
#     - protocol: TCP
#       port: 80
#       targetPort: 8080
#   type: LoadBalancer

