apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  meshConfig:
    defaultConfig:
      externalServiceRegistries:
      - name: secureauth-registry
        services: ["secureauth-service.example.com"]