apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: your-app-vs
spec:
  hosts:
  - your-app.example.com
  http:
  - route:
    - destination:
        host: your-app-service
        port:
          number: 80
    match:
    - uri:
        prefix: /api
  authentication:
    name: external-auth-policy  # Name of the AuthenticationPolicy