apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: your-microservice
spec:
  hosts:
    - your-microservice.example.com
  http:
    - route:
        - destination:
            host: your-microservice
        headers:
          request:
            authorization:
              required: true
      fault:
        abort:
          httpStatus: 401
          percentage:
            value: 100