kube-vip:
  image:
    repository: plndr/kube-vip
    tag: 0.3.3
  vipIP: <Your-VIP-IP>
  networkInterface: <Your-Network-Interface>

istio:
  gateway:
    name: my-gateway

my-service:
  name: my-service
  appSelector:
    app: my-app
  port:
    targetPort: 8080

    